name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        qt_ver: [6.6.3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          modules: qtbase qtgui
      - name: Configure
        run: cmake -S . -B build -DQTDOCTXTEMPLATE_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: ctest --test-dir build --output-on-failure
      - name: Install
        run: cmake --install build --prefix install
      - name: Config Package Check
        run: |
          cmake -S examples/minimal -B build-consume -DCMAKE_PREFIX_PATH=${{ github.workspace }}/install
          cmake --build build-consume
