name: Sanitizers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 0'

jobs:
  asan-ubsan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt (minimal)
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.3
          modules: qtbase qtgui
      - name: Configure (ASan/UBSan)
        env:
          CXXFLAGS: "-fsanitize=address,undefined -fno-omit-frame-pointer -O1"
          CFLAGS: "-fsanitize=address,undefined -fno-omit-frame-pointer -O1"
          LDFLAGS: "-fsanitize=address,undefined"
        run: cmake -S . -B build -DQTDOCTXTEMPLATE_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: ctest --test-dir build --output-on-failure
